### ISSUE TITLE
Saved automata not loading

### ISSUE THREAD

**Issue by gregth** [dionyziz/Automata#54]
Trying to load saved automata (using share links) is working inproperly. Specifically, sometimes it takes too much time to load the saved NFA and sometimes it doesn't even load it at all.

Example link of saved NFA: http://automata.discrete.gr/##v70

**Comment by vasspilka** [comment]
Try removing the extra # 

http://automata.discrete.gr/#v70

**Comment by gregth** [comment]
The generated links contain a double #. Removing the extra # doesn't seem
to be the solution to the problem. Actually it would seem a good idea the
generated links not to contain a double #, but still I think it has nothing
to do with the initial problem.

**Comment by vasspilka** [comment]
A PR will be much appreciated :)

**Comment by vasspilka** [comment]
My guess would be that if the link contains ONLY a `#` instead of `#v` it will add that extra `#`, also if anything else for that matter for example `#123bebebe` 
:D

**Comment by vasspilka** [comment]
Closing in favor of #55 and #56
