### ISSUE TITLE
Early rejection maintains the wrong step number

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/Automata#9]
In an automaton that early rejects by reaching a state where no states are active before consuming the final symbol, hitting the right arrow key on the keyboard to go to the next state a few times doesn't have any effect. But if thereafter the user presses the left arrow to go to the previous state, the wrong state is highlighted in the runner window.

**Comment by DmitryMyadzelets** [comment]
To reproduce the bug, change the default string `abba` to `cabba`. When Running windows is open, press `Step forward` button once. The first char `c` shall be rejected by the default automaton. Press `Step forward` button fiew times again. The *symbol marker* remains at the same place as it supposed to be. Now, press `Step backward` button once. You'll see that the marker appears in a wrong place.

**Comment by vasspilka** [comment]
I see :) Yeah fixed :)

**Comment by DmitryMyadzelets** [comment]
This issue may be closed.
